DROP DATABASE IF EXISTS db_convenientbuy;
CREATE DATABASE db_convenientbuy;

DROP TABLE IF EXISTS db_convenientbuy.user;
CREATE TABLE db_convenientbuy.cb_content (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '',
  category_id BIGINT(20) NOT NULL COMMENT '',
  title VARCHAR(200) DEFAULT NULL COMMENT '',
  sub_title VARCHAR(100) DEFAULT NULL COMMENT '',
  title_desc VARCHAR(500) DEFAULT NULL COMMENT '',
  url VARCHAR(300) DEFAULT NULL COMMENT '',
  pic VARCHAR(400) DEFAULT NULL COMMENT '',
  pic2 VARCHAR(400) DEFAULT NULL COMMENT '',
  content DATETIME DEFAULT NULL COMMENT '',
  created DATETIME DEFAULT NULL COMMENT '',
  updated DATETIME DEFAULT NULL COMMENT ''
) COMMENT '首页展示图';


SELECT *
FROM db_convenientbuy.user;
